### ISSUE TITLE
Lights : set dimmable (using "brightness":xx) crashes node-red server

### ISSUE THREAD

**Issue by FredBlo** [fabiobui/node-red-contrib-myhome-bticino#2]
Very nice work !

I tested the lights parts. Works nice for ON / OFF.
Dimmable status (in %) is displayed correctly in node status (and in payload output).
But when setting it as input, it crashes the node-red server.

I included the full logs so I hope it can help to debug :-)

Here's the console info :
````
Command socket error
13 Feb 11:11:38 - [red] Uncaught Exception:
13 Feb 11:11:38 - TypeError: error is not a function
    at Socket.<anonymous> (/data/node_modules/node-red-contrib-myhome-bticino/myhome-utils.js:18:5)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.2.9 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-red-docker@1.2.9 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.


And the full local .log file content
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   'start',
1 verbose cli   '--cache',
1 verbose cli   '/data/.npm',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.14.10
3 info using node@v10.23.2
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.2.9~prestart: node-red-docker@1.2.9
7 info lifecycle node-red-docker@1.2.9~start: node-red-docker@1.2.9
8 verbose lifecycle node-red-docker@1.2.9~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.2.9~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.2.9~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.2.9~start: Args: [ '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"' ]
12 silly lifecycle node-red-docker@1.2.9~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.2.9~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.2.9 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid node-red-docker@1.2.9
16 verbose cwd /usr/src/node-red
17 verbose Linux 3.10.105
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "--no-fund" "start" "--cache" "/data/.npm" "--" "--userDir" "/data"
19 verbose node v10.23.2
20 verbose npm  v6.14.10
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.2.9 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.2.9 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
````

**Comment by FredBlo** [comment]
I looked at the code. If my lightid is 'x' and brightness 50, the current code generates a BUS request which looks like :
> ``*#1*x*#1*150*255##``

This is not compliant to what OpenWebNet accepts, and seems to be a read info (#1 instead of 1 as 'Who')

see : 
https://github.com/fabiobui/node-red-contrib-myhome-bticino/blob/d539d2bad8e636520bebca9ec7cdc2afaa5776fe/myhome-light.js#L79

The dimmer request (when sent) is supposed to look like (or at least it is what my dimmer buttons generate) :
>``*1*x*5##``

The brightness is supposed to be between 20% (=2) and 100% (=10).
The new code line could be (all set on a single line, could be more readable on multiple ones):
``'*1*' + Math.min(10,Math.max(2,Math.round(requested_brightness/10)))  + '*' + config.lightid + '##'; ``
